A,4,(intsr)
A',8,"Dear darlin, your mom"
A',8,"That you're wanted to do"
A'',8,"And yes, they're in shock"
B,8,"If we"
B,8,"If we"
A',8,"I remember"
A'',8,"And you were my"
B,8,"If we"
B,8,"If you"
A',8,"You and I, we're like"
A',8,"And never talk small"
B,8,"If we were their condemnations"
B,8,"If we"
A',6...,"We need reflection"
